color: fuchsia
description: null
fieldLayouts:
  668387eb-e38e-444d-bb63-d0cd56d48d95:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-09T12:55:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 772faef9-d08d-4f6c-9193-df0f59cb0731
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-25T13:05:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5572dbe1-afd5-430a-ab5f-7ce1c89540fb # Heading And Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91e8b84c-ee2b-4130-bcd6-f48dedfd41d0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-09T13:07:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 839c2646-ed8d-4c8f-895b-ec17db8d3a09 # Expandable Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b1b4ea6-8f65-47bc-b866-d5644d80a60c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-24T13:39:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a04234cf-f292-41ee-867f-ec45d78adace # Accordion Display Mode
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73344764-daff-42ca-bb60-cd2591e3cc64
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-25T09:45:45+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a04234cf-f292-41ee-867f-ec45d78adace # Accordion Display Mode
                  layoutElementUid: 73344764-daff-42ca-bb60-cd2591e3cc64
                  operator: in
                  uid: 268a47c0-0291-44b9-adb6-f3bd649fe06e
                  values:
                    - accordionWithSingleImage
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 4227d4d3-78dc-46a0-a113-6fca08453b44 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbd7880c-a615-42fe-a7ed-05328feab83f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-30T12:33:32+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: a04234cf-f292-41ee-867f-ec45d78adace # Accordion Display Mode
                  layoutElementUid: 73344764-daff-42ca-bb60-cd2591e3cc64
                  operator: in
                  uid: 8645be91-3345-4aa4-a72a-fbafe19aa22f
                  values:
                    - accordionWithChangingImage
                    - accordionWithSingleImage
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 04ad650c-288d-43f5-bd23-668bf6ac8bba # Column Reverse 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfb6a879-6651-4919-82ad-36e611d31ad0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-25T12:33:18+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 9153758b-1dae-4f56-8a5f-b4542f96caeb
            userCondition: null
          -
            dateAdded: '2024-12-09T13:10:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f4361f14-4011-4ce7-97d6-9a625645844f # Block Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4ecf47a-c9ab-4167-91db-312405ef1807
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-25T12:43:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9f6986e8-9af9-4468-ac6f-59344201199f # Accordion Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b39a4981-0d44-4122-88a5-7d3e68d0ee08
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 0cb627f2-bf2b-4116-bb8b-e3026d563d4d
        userCondition: null
handle: accordion
hasTitleField: false
icon: plus
name: Accordion
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
