color: orange
description: null
fieldLayouts:
  65e50bbf-2352-40c7-aca8-d395a716c981:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-14T07:46:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d10a2b0f-2d53-4e51-afbc-890e28ee6b0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T07:48:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4227d4d3-78dc-46a0-a113-6fca08453b44 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12113dfc-119e-44b8-9dac-4789598f319a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T07:48:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76d00c6d-1cfa-4977-8322-0bfa2e297408 # Plain Text
            handle: imageCaption
            includeInCards: false
            instructions: null
            label: 'Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c73e0d5-20ea-4441-bc42-1c08206022dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d7ed62e4-b669-4bb3-90af-a03cbeabe4f1
        userCondition: null
handle: galleryImage
hasTitleField: false
icon: images
name: 'Gallery Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
