color: violet
description: null
fieldLayouts:
  9cff094c-9ef7-4398-9ed8-a717b0edc657:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-16T12:53:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Section Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 716e6472-433d-47bc-a527-98cfe6f66375
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-16T14:15:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bc7bef00-73a0-44bf-a72b-cbc3acd82660 # Matrix Row
            handle: null
            includeInCards: false
            instructions: null
            label: 'Matrix Columns'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ea951fa-1f78-4e4a-8e0a-40166d2315f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T06:51:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a9ccbd30-ea9b-4c64-8527-b375a8ef10a4 # Section Style 
            handle: null
            includeInCards: false
            instructions: null
            label: 'Section Style'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b451ebf4-e5f8-4595-a097-9d5fee7e693c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 677a6c2a-c4b7-4272-94d6-2300678b156c
        userCondition: null
handle: matrixRowET
hasTitleField: false
icon: table-rows
name: 'Matrix Row'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{title}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
