color: null
description: null
fieldLayouts:
  8d3bdd04-a48f-4e7e-b9fc-f4887c8e288d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-02T13:08:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 20e9115d-c70d-4a5f-81d9-dca35edcd6bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-03T13:57:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aecd212f-7bee-4094-8a2f-7be8c709545b # Single Select
            handle: null
            includeInCards: false
            instructions: null
            label: Blog
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 067358f0-cd72-4f45-9a2a-56480e7e6de3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-02T13:16:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76d00c6d-1cfa-4977-8322-0bfa2e297408 # Plain Text
            handle: reviewerName
            includeInCards: false
            instructions: null
            label: 'User Name'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: deb6aa30-1cde-4bcf-b89a-807819d3fe47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-02T13:16:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 78507861-ed14-4d42-a42d-525ddca79548 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ae013bd-3d80-44d9-86e1-5fad5ceba69e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-02T13:16:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67b7863f-e411-46fb-a8f5-7cf4e4df7529 # Short Description
            handle: comment
            includeInCards: false
            instructions: null
            label: Comment
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c444cc1-dbc6-4642-8a94-c96bedd8a5c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-18T09:40:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d884fdd-3cb4-442f-bfb1-c92245f1089e # Number
            handle: rate
            includeInCards: false
            instructions: null
            label: Rate
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 882a9ae6-cdf9-4462-a92b-87d29beb6bb9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-03T13:37:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 67b7863f-e411-46fb-a8f5-7cf4e4df7529 # Short Description
            handle: reply
            includeInCards: false
            instructions: null
            label: Reply
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8899de1b-a7ef-40b5-b0df-e9d13c9fb234
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-04T12:17:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76d00c6d-1cfa-4977-8322-0bfa2e297408 # Plain Text
            handle: parentId
            includeInCards: false
            instructions: null
            label: ParentId
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0c22fb9-de1d-42dc-bdfa-bd172874f9f0
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SlugConditionRule
                  operator: empty
                  uid: 9e18d39d-ca1c-47b5-8ee8-90b328af23e3
                  value: ''
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 50
        name: Content
        uid: 992e588f-aa87-4554-b790-7ab344b9ed7b
        userCondition: null
handle: review
hasTitleField: true
icon: null
name: Review
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
