defaultPlacement: end
fieldLayouts:
  8abe926b-5127-423a-9b96-598f96cd16d1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-07T06:22:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 2758041f-3135-4658-843c-f4f10330ac1d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-07T06:22:57+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: mycompany\menumanager\fieldlayoutelements\NodeTypeElements
            uid: b30bec20-7476-48a4-9add-305ce205b81a
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2025-09-07T06:22:57+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\NewWindowField
            uid: e2441701-daa1-4180-93af-01ce26221d55
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 12e66019-77b2-493e-91ad-50ccfb7bd7e1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-09-07T06:22:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\UrlSuffixField
            uid: f470a4e2-3127-4caf-a3b2-d80b9384d3e0
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-09-07T06:22:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\ClassesField
            uid: 42451a50-5432-400c-a107-40ba07e3d45f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-09-07T06:22:57+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\CustomAttributesField
            uid: 4a2bf185-b3e9-450e-b7b7-fdc647e1f539
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 71e2e6e8-f33e-4c2f-8165-d6395063ac2f
        userCondition: null
handle: footermenu
instructions: ''
maxNodes: null
name: 'Footer Menu'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  mycompany\menumanager\nodetypes\CustomType:
    enabled: '1'
  mycompany\menumanager\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabled: true
sortOrder: 2
structure:
  maxLevels: null
  uid: 3804f69b-9e47-45d2-88ce-c238fd972407
