defaultPlacement: end
fieldLayouts:
  0aa801b1-8423-4fee-8671-0740b5a827e7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-07T05:01:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: af6820da-b2b7-425e-879d-1bcee8607be9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-07T05:01:17+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: mycompany\menumanager\fieldlayoutelements\NodeTypeElements
            uid: bf96cad9-fde9-4458-938b-e4bd4983e38b
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2025-09-07T05:01:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\NewWindowField
            uid: a880ed94-c49a-4aa2-977b-2e6ebb2e34a8
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 7ab5f7eb-1f92-418f-93c2-80bed01c1133
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-09-07T05:01:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\UrlSuffixField
            uid: 3d1af86c-ccab-4045-9df6-d706eab32871
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2025-09-07T05:01:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\ClassesField
            uid: 349cb47c-06cc-4c23-98ce-e66bc55c6403
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2025-09-07T05:01:17+00:00'
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            mandatory: false
            orientation: null
            providesThumbs: false
            requirable: true
            required: false
            tip: null
            translatable: false
            type: mycompany\menumanager\fieldlayoutelements\CustomAttributesField
            uid: c9ff4858-f688-4401-9c05-622faadd8ceb
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 2010965e-cf0a-448a-a6f8-863025c86775
        userCondition: null
handle: menu
instructions: null
maxNodes: null
name: menu
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  mycompany\menumanager\nodetypes\CustomType:
    enabled: '1'
  mycompany\menumanager\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabled: true
sortOrder: 1
structure:
  maxLevels: null
  uid: 9039ad1d-37bb-4f47-a397-6afa35152352
