columnSuffix: null
handle: colorcode
instructions: null
name: 'Color Code'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
