columnSuffix: null
handle: singleSelect
instructions: null
name: 'Single Select'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:bf4cc05a-ef9b-449d-a10b-f1269eb781b8'
    - 'section:584ca52e-5780-48a4-8237-eafd87560cf5'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
