columnSuffix: null
handle: switchOff
instructions: null
name: 'Switch Default Off'
searchable: false
settings:
  default: false
  offLabel: 'Off'
  onLabel: 'On'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
