columnSuffix: null
handle: typography
instructions: null
name: Typography
searchable: false
settings:
  createButtonLabel: 'Add Typography Style'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c2049493-e863-498c-87d5-6b6e67ebad0d # Typography
  includeTableView: false
  maxEntries: 1
  minEntries: 1
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
