defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f57baac9-d0c0-4a0c-bdc7-568181cbc836 # Blog 
handle: blogs
maxAuthors: 1
name: Blogs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: entries/channels/blog.twig
    uriFormat: 'blogs/{slug}'
type: channel
