defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: eb5b5932-0853-4605-917f-7c5ddc16a740 # Footer
handle: footer
maxAuthors: 1
name: Footer
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: footer
type: single
