defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a0defa36-1e21-4f86-adc2-e7eedf1b4e37 # General
handle: general
maxAuthors: 1
name: General
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
