defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b5d8fb76-3f66-4448-88d9-4beed0ee49f7 # Header
handle: header
maxAuthors: 1
name: Header
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: header
type: single
