defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fee4a1a9-1a3d-4d2c-b9f6-6f31206ce3b4 # Product
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d70c2279-51bd-4f14-85f1-cea184ebb831: # Craft CMS
    enabledByDefault: true
    hasUrls: true
    template: entries/channels/product.twig
    uriFormat: 'products/{slug}'
type: channel
